general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]
[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.7
# opacity = 1
blur = true
startup_mode = "Maximized"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "regular" }
size = 12
